# Generated by Django 4.1.5 on 2023-01-14 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adotar', '0002_alter_pedidoadocao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoadocao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
